security:
    
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    
    firewalls:
        login:
            pattern: ^/account|/token
        
        api:
            pattern:   ^/api
            stateless: true
            jwt: ~
    
    access_control:
        - { path: ^/account, roles: PUBLIC_ACCESS }
        - { path: ^/token, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER }